#!/usr/bin/env bash
#
# Regenerate docs/scan.svg and the text block in README.md from ONE capsize
# run, against a live fixture cluster.
#
#   ./docs/capture.sh                 # re-capture and rewrite the docs
#   ./docs/capture.sh --check         # verify the committed docs agree (no writes)
#
# Why this is a script and not three commands.
#
# capsize's absolute scores are host-specific: the ceiling term is node
# allocatable memory, so the same workload scores 12.2 on a 2.6Gi node and
# 30.43 on a 6.55Gi one. That is correct behavior - it is why
# test/e2e/assert_oracle.py asserts orderings and ratios instead of fixed
# numbers - but it means a picture captured on one host and prose written
# from another produce a README that contradicts itself. That happened: the
# image showed eight findings above a summary that counted nine.
#
# So there is exactly one capture here. The SVG, the text equivalent and every
# figure quoted in prose all come from the same bytes, and --check fails if
# they ever stop agreeing.
set -euo pipefail

cd "$(dirname "$0")/.."

NAMESPACE="${CAPSIZE_NS:-sandbox}"
# Spelled out rather than `mktemp -t`: BSD mktemp treats the argument as a
# prefix, GNU requires a template ending in X's, and the two disagree about
# what -t means. This form is identical on both.
RAW="$(mktemp "${TMPDIR:-/tmp}/capsize-capture.XXXXXX")"
trap 'rm -f "$RAW" "$RAW".txt' EXIT

# Figures quoted in README.md and DESIGN.md prose, outside the captured block.
# Every one of them must appear in the capture; that is the invariant this
# script exists to hold. Add a figure here when you quote one in prose.
PROSE_FIGURES=(
  # README, "The idea in one output block" and "Why the two axes fight"
  "12.2" "122.6" "128.9" "512Mi" "51Mi" "461Mi" "2.6Gi"
  # DESIGN.md section 9, the effective-resources worked example
  "2.32"
)

check_only=false
[[ "${1:-}" == "--check" ]] && check_only=true

need() { command -v "$1" >/dev/null || { echo "need $1 on PATH" >&2; exit 1; }; }
need python3
# --check reads only committed files, so it needs neither freeze nor a
# cluster. That is deliberate: it means CI can hold this invariant on every
# push, instead of it depending on somebody remembering to re-run the capture.
$check_only || { need freeze; need go; }

# --- the one run ----------------------------------------------------------
#
# Through a pty, because capsize emits no color when its stdout is not a
# terminal - the SVG would be a grey wall otherwise.
#
# python3 rather than script(1): script needs a controlling terminal on its
# own stdin, which it does not have under CI or any other non-interactive
# runner, and the two platforms spell its arguments differently. This has no
# BSD/GNU split and needs no tty of its own.
capture() {
  go build -o ./capsize .
  python3 - "$RAW" "$NAMESPACE" <<'PYCAP'
import fcntl, os, pty, struct, sys, termios

out, namespace = sys.argv[1], sys.argv[2]

pid, fd = pty.fork()
if pid == 0:
    os.execvp("./capsize", ["./capsize", "-n", namespace])

# Wide enough that nothing capsize prints could be folded by a terminal that
# assumed 80 columns.
fcntl.ioctl(fd, termios.TIOCSWINSZ, struct.pack("HHHH", 60, 200, 0, 0))

with open(out, "wb") as f:
    try:
        while True:
            data = os.read(fd, 4096)
            if not data:
                break
            f.write(data)
    except OSError:
        pass            # the child closed the pty; that is how this ends

_, status = os.waitpid(pid, 0)
code = os.waitstatus_to_exitcode(status)
# capsize exits 2 when a threshold is crossed, which is a successful scan.
if code not in (0, 2):
    sys.exit("capsize exited %d" % code)
PYCAP
  # The line discipline turns every \n into \r\n on the way out.
  perl -pi -e 's/\r$//' "$RAW"
  # The text equivalent is the same bytes with the escapes removed.
  perl -pe 's/\e\[[0-9;]*m//g' "$RAW" > "$RAW".txt
}

if $check_only; then
  cp docs/scan.txt "$RAW".txt
else
  capture
  cp "$RAW".txt docs/scan.txt

  # freeze falls into its interactive form when it cannot parse an option, and
  # then blocks forever on stdin. Closing stdin makes that a fast failure
  # rather than a hung CI job.
  freeze "$RAW" --config docs/freeze.json --output docs/scan.svg < /dev/null
fi

# --- the text block in README.md ------------------------------------------
python3 - "$RAW".txt "$check_only" <<'PY'
import pathlib, sys

capture = pathlib.Path(sys.argv[1]).read_text()
check_only = sys.argv[2] == "true"

BEGIN = "<!-- BEGIN capture: generated by docs/capture.sh; do not edit -->"
END = "<!-- END capture -->"

readme = pathlib.Path("README.md")
s = readme.read_text()
i, j = s.find(BEGIN), s.find(END)
if i < 0 or j < 0:
    sys.exit(f"README.md is missing the capture markers:\n  {BEGIN}\n  {END}")

block = f"{BEGIN}\n\n```\n$ capsize -n sandbox\n{capture.rstrip()}\n```\n\n"
current = s[i:j]
if check_only:
    if current != block:
        sys.exit("README.md's capture block does not match docs/scan.txt.\n"
                 "Run docs/capture.sh against the fixture to regenerate both.")
else:
    readme.write_text(s[:i] + block + s[j:])
PY

# --- every prose figure has to be in the capture --------------------------
missing=()
for fig in "${PROSE_FIGURES[@]}"; do
  grep -qF -- "$fig" "$RAW".txt || missing+=("$fig")
done
if (( ${#missing[@]} )); then
  echo "these figures are quoted in prose but are not in this capture:" >&2
  printf '  %s\n' "${missing[@]}" >&2
  echo >&2
  echo "Absolute scores move with node allocatable memory, so a re-capture on a" >&2
  echo "different host changes them. Update the prose in README.md and DESIGN.md" >&2
  echo "to this capture's numbers, and the caption that names the host." >&2
  exit 1
fi

$check_only && echo "docs/scan.svg, docs/scan.txt, README.md and DESIGN.md agree" \
            || echo "regenerated docs/scan.svg, docs/scan.txt and README.md from one run"
